# Generated by Django 4.2.2 on 2023-06-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
