# Generated by Django 4.2.2 on 2023-06-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_web', '0002_alter_telegramuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='telegram_id',
            new_name='tg_id',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='user',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='tg_auth_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='tg_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='tg_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='tg_photo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='tg_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
