# Generated by Django 4.2.1 on 2023-06-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_web', '0002_alter_post_tags_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='text',
        ),
    ]
