# Generated by Django 4.2.2 on 2023-06-23 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_web', '0002_alter_telegramuser_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
